### ISSUE TITLE
Google Developers ML Summit (Cambridge, MA) Aug 28

### ISSUE THREAD

**Issue by reshamas** [WiMLDS/conferences#31]
ML Summit is coming up on August 28 in Cambridge, and we're looking for good women speakers to give talks on intermediate-advanced Machine Learning/AI concepts or demos (30 minutes). We're also looking for a speaker for a 10-minute lightning talk. 

Here's the CFP form, please feel free to share it within your network.
https://docs.google.com/forms/d/e/1FAIpQLSe7P8tlfuEwloC9mUgmK8nM-3Naqhv1SIibOOXUjfOO--pdQQ/viewform

https://events.withgoogle.com/mlsummit19/

**Comment by prith13** [comment]
added to the 2019_listings.md file!
