### ISSUE TITLE
O’Reilly TensorFlow World | October 28–31, 2019 | Santa Clara, CA

### ISSUE THREAD

**Issue by reshamas** [WiMLDS/conferences#32]
O’Reilly TensorFlow World | October 28–31, 2019 | Santa Clara, CA

The inaugural O’Reilly TensorFlow World is the first event of its kind—gathering the TensorFlow team and machine and deep learning experts to share best practices, promising (and tested) use cases, and a firsthand look at TensorFlow 2.0. Join us and stay ahead of what's coming. Register today to save over $800 on most passes with Best Price and our 20% partner discount code: UGWMLDS. But hurry—Best Price ends on August 9.
https://www.oreilly.com/pub/cpc/258529
Tweets

Don’t miss out on Best Price for #TFWorld in Santa Clara! Save over $800 with our code @discount code@ when you register before August 9. Sign up today.
https://oreil.ly/2yde1lt

We're proud to partner with #TFWorld in Santa Clara, October 28–31. Save 20% w/code UGWMLDS.
https://oreil.ly/2MidkzB

Join us at TensorFlow World in Santa Clara, October 28–31, to tap into this vibrant community and see TensorFlow’s power in action. #TFWorld
https://oreil.ly/2MdRRaS

**Comment by prith13** [comment]
added to the 2019_listings.md file!
