### ISSUE TITLE
The O’Reilly Strata Data Conference | March 15–18, 2020 | San Jose

### ISSUE THREAD

**Issue by reshamas** [WiMLDS/conferences#33]
The O’Reilly Strata Data Conference | March 15–18, 2020 | San Jose

The O’Reilly Strata Data Conference is returning to San Jose March 15–18. We're looking for compelling data case studies, proven best practices, effective new analytic approaches, deep technological expertise, and high-level executive briefings, as well as insight into how the strategic use of data can shape the future of both business and technology.

If you've got a great idea, we'll put you in front of the most prominent and engaged audience in data.

Check out our tips for submitting a great proposal and the lists of topics we're interested in covering, and send us your best ideas by September 5.

Submit your proposal now. –>
https://www.oreilly.com/pub/cpc/256233
Tweets

Now's the time to share your best data ideas for #StrataData San Jose. The call for proposals closes September 5.
https://oreil.ly/2ydTIEA

Inspired to speak at the next #bigdata event? The #StrataData San Jose 2020 call for proposals is open until September 5.
https://oreil.ly/2Mg6OcD

**Comment by prith13** [comment]
added to the 202_listings.md file and should be in the main readme now!
