### ISSUE TITLE
Move 2020 conferences from 2019 folder 

### ISSUE THREAD

**Issue by zuzannna** [WiMLDS/conferences#35]

**Comment by prith13** [comment]
have we been updating the 2019_listings.md file with 2020 conferences? I don't see a 2020 table in there. Also, I don't see a 2019 folder heh!

**Comment by reshamas** [comment]
@prith13 @zuzannna 
I would prefer to have the upcoming 2020 conferences on the main README.md since it's the quickest file to access.  Thanks.
